name: Build and Deploy
on:
  push:
    branches:
      - main    # å½“æ¨é€åˆ° main åˆ†æ”¯æ—¶è§¦å‘
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. æ£€å‡ºä»£ç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@master

      # 2. å®‰è£…ä¾èµ–å¹¶æ„å»º
      - name: Install & Build
        run: |
          npm install
          npm run build

      # 3. éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist          # æ„å»ºäº§ç‰©ç›®å½•
          BRANCH: gh-pages      # ç›®æ ‡åˆ†æ”¯
